excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Demo
  - Tests
disabled_rules:
  - switch_case_alignment
  - cyclomatic_complexity
type_name:
  min_length: 1 # only warning
identifier_name:
  validates_start_with_lowercase: false
  allowed_symbols: "_"

line_length:
  warning: 180
