osx_image: xcode11.3
language: swift

script:
- ./Sources/gdal/prepare_gdal.sh
- cd Tests
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -scheme Tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.3' | xcpretty
