name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-14-xlarge

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'

      - name: Install dependencies
        run: swift package resolve

      - name: Run tests
        run: |
            cd Tests
            set -o pipefail && xcodebuild test -scheme Tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15 Pro' | xcpretty
